name: CI

on:
  push:
    branches: [ ci-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Get updated version of the code
      uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    
    - name: Install dependencies
      run: yarn
    
    - name: Run unit tests
      run: yarn test
      
    - name: Run lint
      run: yarn lint

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run build
      run: yarn build
